[package]
name = "tz-convert"
version = "0.1.0"
edition = "2021"
authors = ["Connor Field <connor@connorfield.com>"]

[dependencies]
chrono = "0.4"
chrono-tz = "0.6"
prettytable = "0.10.0"
colored = "2.0"
dialoguer = "0.9"